-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Name" TEXT NOT NULL,
    "Gender" TEXT NOT NULL,
    "Age" INTEGER NOT NULL,
    "Link" TEXT NOT NULL
);
